-- cols(
--   hotel = col_character(),
--   is_canceled = col_double(),
--   lead_time = col_double(),
--   arrival_date_year = col_double(),
--   arrival_date_month = col_character(),
--   arrival_date_week_number = col_double(),
--   arrival_date_day_of_month = col_double(),
--   stays_in_weekend_nights = col_double(),
--   stays_in_week_nights = col_double(),
--   adults = col_double(),
--   children = col_double(),
--   babies = col_double(),
--   meal = col_character(),
--   country = col_character(),
--   market_segment = col_character(),
--   distribution_channel = col_character(),
--   is_repeated_guest = col_double(),
--   previous_cancellations = col_double(),
--   previous_bookings_not_canceled = col_double(),
--   reserved_room_type = col_character(),
--   assigned_room_type = col_character(),
--   booking_changes = col_double(),
--   deposit_type = col_character(),
--   agent = col_character(),
--   company = col_character(),
--   days_in_waiting_list = col_double(),
--   customer_type = col_character(),
--   adr = col_double(),
--   required_car_parking_spaces = col_double(),
--   total_of_special_requests = col_double(),
--   reservation_status = col_character(),
--   reservation_status_date = col_date(format = "")
-- )

CREATE TABLE hotel(
	hotel                          VARCHAR(15),
	is_canceled                    INT,
	lead_time                      INT,
	arrival_date_year              INT,
	arrival_date_month             VARCHAR(15),
	arrival_date_week_number       INT,
	arrival_date_day_of_month      INT,
	stays_in_weekend_nights        INT,
	stays_in_week_nights           INT,
	adults                         INT,
	children                       INT,
	babies                         INT,
	meal                           VARCHAR(15),
	country                        VARCHAR(7),
	market_segment                 VARCHAR(15),
	distribution_channel           VARCHAR(15),
	is_repeated_guest              INT,
	previous_cancellations         INT,
	previous_bookings_not_canceled INT,
	reserved_room_type             VARCHAR(1),
	assigned_room_type             VARCHAR(1),
	booking_changes                INT,
	deposit_type                   VARCHAR(15),
	agent                          INT,
	company                        INT,
	days_in_waiting_list           INT,
	customer_type                  VARCHAR(15),
	adr                            VARCHAR(7),
	required_car_parking_spaces    INT,
	total_of_special_requests      INT,
	reservation_status             VARCHAR(15),
	reservation_status_date        VARCHAR(7)
);

COPY hotel FROM "hotel_bookings.csv" CSV HEADER;
